import { createCanvas, loadImage } from "canvas";
import { formatRavMonth } from "../ui/formatRavMonth.js";

export async function generateActivityImage(stats, monthKey) {
  const width = 2000;
  const height = 1000;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  /* ───── Background ───── */
  const bg = ctx.createLinearGradient(0, 0, 0, height);
  bg.addColorStop(0, "#1e1f24");
  bg.addColorStop(1, "#14151a");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  /* ───── Title ───── */
  ctx.fillStyle = "#a2C6Ca";
  ctx.font = "bold 44px 'Times New Roman'";
  ctx.textAlign = "left";
  const dateRangeStr = formatRavMonth(monthKey);
  ctx.fillText(`RAV Monthly activity count | ${dateRangeStr}`, 50, 60);

  /* ───── Prepare entries & sort descending ───── */
  let entries = [
    { label: "Misc", value: stats.misc, colors: ["#4ade80", "#15803d"] },
    { label: "Events", value: stats.event, colors: ["#60a5fa", "#1d4ed8"] },
    { label: "Roleplays", value: stats.roleplay, colors: ["#facc15", "#a16207"] },
    { label: "Raids", value: stats.raid, colors: ["#f87171", "#991b1b"] }
  ];

  entries.sort((a, b) => b.value - a.value);
  const total = entries.reduce((acc, e) => acc + e.value, 0);

  /* ───── Grid lines ───── */
  const max = Math.max(...entries.map(e => e.value), 1);
  ctx.strokeStyle = "#3a3b40";
  ctx.lineWidth = 1;
  ctx.font = "14px 'Times New Roman'";
  ctx.fillStyle = "#aaa";

  for (let i = 0; i <= max; i += Math.ceil(max / 5)) {
    const y = 500 - (i / max) * 300;
    ctx.beginPath();
    ctx.moveTo(80, y);
    ctx.lineTo(width - 60, y);
    ctx.stroke();
    ctx.fillText(i, 50, y + 5);
  }

  /* ───── Draw bars ───── */
  const barWidth = 120;
  const gap = 80;
  const startX = 120;
  const baseY = 500;

  entries.forEach((e, i) => {
    const barHeight = (e.value / max) * 300;
    const x = startX + i * (barWidth + gap);
    const y = baseY - barHeight;

    const gradient = ctx.createLinearGradient(x, y, x, baseY);
    gradient.addColorStop(0, e.colors[0]);
    gradient.addColorStop(1, e.colors[1]);
    ctx.fillStyle = gradient;

    ctx.shadowColor = "rgba(0,0,0,0.5)";
    ctx.shadowBlur = 14;
    ctx.shadowOffsetY = 5;
    ctx.fillRect(x, y, barWidth, barHeight);
    ctx.shadowColor = "transparent";

    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 26px 'Times New Roman'";
    ctx.textAlign = "center";
    ctx.fillText(e.value, x + barWidth / 2, y - 14);

    ctx.save();
    ctx.translate(x + barWidth / 2, baseY + 50);
    ctx.rotate(-Math.PI / 6);
    ctx.font = "18px 'Times New Roman'";
    ctx.fillStyle = "#d1d5db";
    ctx.textAlign = "right";
    ctx.fillText(e.label, 0, 0);
    ctx.restore();
  });

  /* ───── Total summary ───── */
  ctx.textAlign = "right";
  ctx.fillStyle = "#22c55e";
  ctx.font = "bold 32px 'Times New Roman'";
  ctx.fillText(`Total Posts: ${total}`, width - 60, 140);

  /* ───── Footer ───── */
  ctx.textAlign = "center";
  ctx.fillStyle = "#888";
  ctx.font = "14px 'Times New Roman'";
  ctx.fillText("Generated by RAV Media Manager", width / 2, height - 30);

  return canvas.toBuffer();
}
